### ISSUE TITLE
Version 2 is not available to download due to module naming issues

### ISSUE THREAD

**Issue by swithek** [barthr/newsapi#6]
Neither `go get github.com/barthr/newsapi` nor `go get github.com/barthr/newsapi@v2.0.0` retrieve the latest version of this package. 

It seems this is caused by [incorrect v2 module naming](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

**Comment by swithek** [comment]
https://pkg.go.dev/github.com/barthr/newsapi?tab=versions only detects v1 as well.

**Comment by barthr** [comment]
Hi @swithek, thanks for opening this issue. I will find some time today to fix it!

**Comment by barthr** [comment]
Hi @swithek, it is fixed. Running `go get github.com/barthr/newsapi` will fetch `v1.3.0` which contains the code from the latest master branch, this is actually the same code as used in v2. I will look at replacing v2 since it doesn't make much sense

**Comment by swithek** [comment]
I think v2.x releases and tags can be deleted altogether. Since nobody was able to download them anyway, there shouldn't be any issues.

**Comment by barthr** [comment]
Indeed :+1:
